import {createGame,act,actions,CHAPTERS,VERSION,isValidSave} from './engine.js';
import {oshn,isha,foe,bell} from './art.js';
import {startAudio,setAudio,setScene,sound} from './audio.js';
const app=document.querySelector('#app'),dialog=document.querySelector('#dialog');
const SAVE='aster-adventure-v1', PREF='aster-preferences-v1';
const backgrounds=['garden','orchard','observatory'];
const icon={sound:'<path d="M3 8h4l5-4v16l-5-4H3V8Z"/><path d="M16 8q5 4 0 8m3-11q8 7 0 14"/>',mute:'<path d="M3 8h4l5-4v16l-5-4H3V8Z"/><path d="m16 9 6 6m0-6-6 6"/>',book:'<path d="M3 4q5-2 9 1 4-3 9-1v15q-5-2-9 1-4-3-9-1V4Zm9 1v15"/>',help:'<circle cx="12" cy="12" r="9"/><path d="M9 9a3 3 0 1 1 4 3q-1 .7-1 2m0 2v1"/>',settings:'<path d="M4 7h16M4 17h16"/><circle cx="9" cy="7" r="3"/><circle cx="16" cy="17" r="3"/>',home:'<path d="m3 11 9-8 9 8M6 9v12h12V9m-8 12v-7h4v7"/>'};
const symbols={strike:'⟡',chime:'♧',mend:'✦',guard:'◇',harmony:'☽',investigate:'✧',travel:'→',continue:'♪','upgrade-heart':'♡','upgrade-voice':'♬','upgrade-thread':'∞',retry:'↻',next:'→'};
let state=null,saved=null,title=true,busy=false,saveOk=true,prefs={sound:true,reduced:false,tutorial:false},timer;
try{prefs={...prefs,...JSON.parse(localStorage.getItem(PREF)||'{}')};const candidate=JSON.parse(localStorage.getItem(SAVE)||'null');if(isValidSave(candidate))saved=candidate;}catch{}
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const svg=s=>`<svg viewBox="0 0 24 24" aria-hidden="true">${icon[s]}</svg>`;
const pips=(n,max,cls='')=>`<span class="energy ${cls}">${Array.from({length:max},(_,i)=>`<span class="pip ${i<n?'on':''}"></span>`).join('')}</span>`;
function savePrefs(){try{localStorage.setItem(PREF,JSON.stringify(prefs));}catch{}document.body.classList.toggle('reduce-motion',prefs.reduced);}
function save(){try{localStorage.setItem(SAVE,JSON.stringify(state));saved=state;saveOk=true;}catch{saveOk=false;}}
function topbar(){return `<header class="topbar"><button class="brand" data-ui="home" aria-label="Return to title">${bell}<span>Xenaland</span></button>${!title?`<div class="chapter-bar"><div class="eyebrow">${state.phase==='ending'?'The end of a beginning':CHAPTERS[state.chapter].title.split(' · ')[0]+' · The journey'}</div><h2>${esc(CHAPTERS[state.chapter].location)}</h2><div class="journey-dots" aria-label="${state.battlesWon} of 6 encounters complete">${Array.from({length:6},(_,i)=>`<span class="${i<state.battlesWon?'done':''}"></span>`).join('')}</div></div>`:''}<nav class="toolbar" aria-label="Game menu">${!title?`<span class="save-note">${saveOk?'PROGRESS SAVED':'SAVING UNAVAILABLE'}</span>`:''}<button class="tool" data-ui="audio" aria-label="${prefs.sound?'Mute sound':'Enable sound'}" title="${prefs.sound?'Mute sound':'Enable sound'}">${svg(prefs.sound?'sound':'mute')}</button><button class="tool" data-ui="journal" aria-label="Open journey journal" title="Journey journal">${svg('book')}</button><button class="tool" data-ui="help" aria-label="How to play" title="How to play">${svg('help')}</button><button class="tool" data-ui="settings" aria-label="Settings" title="Settings">${svg('settings')}</button></nav></header>`;}
function titleScreen(){return `<main class="title-screen" data-phase="title"><div class="title-rule"><span class="eyebrow">A small adventure about beginning again</span></div><h1>The Last Bell<br><em>of Xenaland</em></h1><p class="intro">The world has forgotten morning.<br>Perhaps you can remind it.</p><div class="title-actions">${saved?`<button class="primary" data-ui="resume">${saved.completed?'Revisit the ending':'Continue your journey'} <span>→</span></button><button class="text-button" data-ui="new">Begin anew</button>`:`<button class="primary" data-ui="new">Begin the journey <span>→</span></button>`}</div><div class="title-caption"><span>TURN-BASED ADVENTURE</span><span>15–25 MINUTES</span><span>A COMPLETE STORY</span></div><div class="title-figure">${oshn()}</div><div class="title-moth">${isha()}</div><div class="footer-note">For the things we carry.<br>For the things we let become the sea.</div></main>`;}
function actorStage(){return `<div class="stage-ground"></div>${state.storyAfter==='ending'?'<div class="redeemed-actor"><img class="painted-character" src="./assets/vadish.webp" alt="Vadish, now a loving wizard"></div>':''}<div class="hero-actor">${oshn()}</div>${state.phase==='ending'?'':`<div class="moth-actor">${isha()}</div>`}`;}
function actionButtons(options=actions(state)){return `<div class="actions">${options.map((a,i)=>`<button class="action" data-action="${esc(a.id)}" ${a.disabled||busy?'disabled':''}><span class="key">${i+1}</span><span class="action-icon" aria-hidden="true">${symbols[a.id]||'✧'}</span><strong>${esc(a.label)}</strong>${a.description?`<small>${esc(a.description)}</small>`:''}</button>`).join('')}</div>`;}
function storyScreen(){const l=state.story[state.storyIndex],opts=actions(state);return `<main class="game" data-phase="story" data-encounter="${state.encounter}"><section class="stage explore-stage">${actorStage()}<div class="scene-label"><div class="eyebrow">${state.encounter===0&&state.storyAfter==='explore'?'Where a story begins':esc(CHAPTERS[state.chapter].title)}</div></div></section><section class="interface story-ui"><div class="speaker">${esc(l.speaker)}</div><p class="story-text">${esc(l.text)}</p>${opts.length===1?`<button class="primary" data-action="${opts[0].id}">${state.storyAfter==='ending'&&state.storyIndex===5?'Ring with Vadish':esc(opts[0].label)} <span>→</span></button>`:actionButtons(opts)}<span class="page-count">${String(state.storyIndex+1).padStart(2,'0')} / ${String(state.story.length).padStart(2,'0')} <span class="desktop-hint"> · SPACE TO CONTINUE</span></span></section></main>`;}
function exploreScreen(){return `<main class="game" data-phase="explore" data-encounter="${state.encounter}"><section class="stage explore-stage">${actorStage()}<div class="scene-label"><div class="eyebrow">${esc(CHAPTERS[state.chapter].title)}</div><h3>${esc(state.scene.title)}</h3><p>${esc(state.scene.description)}</p></div><div class="hint-badge">${state.explored?'A memory carried. A little stronger.':'Something here is waiting to be remembered.'}</div></section><section class="interface explore-ui"><h3>${state.explored?'The road is ready when you are.':'Take a moment. The world can wait.'}</h3>${actionButtons()}</section></main>`;}
function battleScreen(){const e=state.enemy,h=state.hero;return `<main class="game" data-phase="battle" data-encounter="${state.encounter}" data-turn="${state.turn}"><section class="stage battle-stage"><div class="encounter-tag">Encounter ${state.encounter+1} of 6</div>${actorStage()}<div class="enemy-actor ${state.encounter===5?'boss':''}">${foe(state.encounter)}</div><div class="enemy-status"><h3>${esc(e.name)}</h3><div class="health-bar" role="progressbar" aria-label="${esc(e.name)} health" aria-valuenow="${e.hp}" aria-valuemax="${e.maxHp}" aria-valuemin="0"><span style="width:${e.hp/e.maxHp*100}%"></span></div><div class="hp-value">${e.hp} / ${e.maxHp}${e.bossPhase===2?' · UNBOUND':''}</div><div class="intent ${e.intent.kind==='heavy'?'heavy':''}"><span class="intent-title">${e.intent.kind==='heavy'?'⚡ Heavy attack gathering':'Next enemy move'}</span><strong>${esc(e.intent.name)} · ${e.intent.damage} damage</strong><small>${esc(e.intent.description)}</small></div></div></section><section class="interface"><div class="battle-top"><div class="hero-stats"><div class="stat-name"><strong>Oshn</strong><span>${h.hp} / ${h.maxHp} health</span></div><div class="health-bar" role="progressbar" aria-label="Oshn health" aria-valuenow="${h.hp}" aria-valuemax="${h.maxHp}" aria-valuemin="0"><span style="width:${h.hp/h.maxHp*100}%"></span></div><div class="energy" aria-label="${h.energy} of ${h.maxEnergy} breath">${Array.from({length:h.maxEnergy},(_,i)=>`<span class="pip ${i<h.energy?'on':''}"></span>`).join('')}<small>${h.energy}/${h.maxEnergy} BREATH</small></div></div><div class="resonance">${isha()}<div><strong>Isha · resonance</strong><div class="energy" aria-label="${state.resonance} of 3 resonance">${Array.from({length:3},(_,i)=>`<span class="pip ${i<state.resonance?'on':''}"></span>`).join('')}<small>${state.resonance}/3</small></div></div></div><div class="turn-label"><strong>Your turn</strong><small>Take your time. You act first.</small></div></div>${actionButtons()}<div class="battle-log"><p>${esc(state.log.slice(-2).join(' '))}</p><button class="text-button" data-ui="battlelog">Battle notes ↗</button></div></section></main>`;}
function rewardScreen(){return `<main class="game" data-phase="reward" data-encounter="${state.encounter}"><section class="stage reward-stage">${actorStage()}<div class="reward-emblem">${bell}<h3>${esc(state.reward.title)}</h3><p>${esc(state.reward.text)}</p><div class="eyebrow">${state.shards} / 6 notes of morning</div></div></section><section class="interface explore-ui"><h3>${state.reward.upgrade?'A little of the song stays with you. Choose a gift.':'You have made room for a little more morning.'}</h3>${actionButtons()}</section></main>`;}
function defeatScreen(){return `<main class="game" data-phase="defeat" data-encounter="${state.encounter}"><section class="stage reward-stage">${actorStage()}<div class="reward-emblem">${bell}<h3>A loose thread.</h3><p>Isha catches you. Even a small light can begin again.</p></div></section><section class="interface explore-ui"><h3>Your journey is safe.</h3>${actionButtons()}<p class="muted" style="font-size:11px;text-align:center">You can also switch to Story mode in Settings.</p></section></main>`;}
function endingScreen(){return `<main class="ending-stage" data-phase="ending"><div class="ending-card">${bell}<div class="eyebrow">The last bell has rung</div><h1>${esc(state.ending.title)}</h1><p>${esc(state.ending.text)}</p><p>${esc(state.ending.epilogue)}</p><div class="ending-stats"><span><strong>6</strong>NOTES RETURNED</span><span><strong>${state.memories.kept+state.memories.released}</strong>MEMORIES FOUND</span><span><strong>1</strong>NEW BEGINNING</span></div><div class="eyebrow">${esc(state.ending.dedication)}</div><div class="ending-buttons"><button class="primary" data-ui="journal">Read your journey</button><button class="secondary" data-ui="credits">Behind the bell</button><button class="text-button" data-ui="home">Back to title</button></div></div></main>`;}
function render(){const active=document.activeElement?.dataset.action;document.body.dataset.chapter=state?.chapter||0;document.querySelector('#world').classList.toggle('dawn',!title&&(state.phase==='ending'||state.storyAfter==='ending'&&state.storyIndex>=6));document.querySelector('.painting').style.backgroundImage=`url('./assets/${backgrounds[title?0:state.chapter]}.webp')`;document.querySelector('.painting').style.filter=!title&&state.phase==='ending'?'sepia(.2) brightness(1.22)':'';document.body.classList.toggle('reduce-motion',prefs.reduced);app.innerHTML=topbar()+(title?titleScreen():({story:storyScreen,explore:exploreScreen,battle:battleScreen,reward:rewardScreen,defeat:defeatScreen,ending:endingScreen}[state.phase])());if(active)app.querySelector(`[data-action="${active}"]:not(:disabled)`)?.focus({preventScroll:true});setScene(state?.chapter||0,!title&&state.phase==='battle');}
function openDialog(titleText,html){dialog.innerHTML=`<button class="close" data-ui="close" aria-label="Close dialog">×</button><h2 id="dialog-title">${titleText}</h2>${html}`;if(!dialog.open)dialog.showModal();}
function help(){openDialog('A little help for the road',`<p>Explore each place, meet its memories, then follow the next note. Your progress saves after every choice on this browser.</p><h3>Listen, then answer.</h3><p>Battles wait for you. The enemy shows its <strong>next move</strong> above its head. Your action always happens first.</p><p><strong>Needle strike</strong> builds breath. <strong>Bright chime</strong> spends 2 breath and cancels a heavy attack. <strong>Shelter</strong> reduces damage by 70% and restores 2 breath. <strong>Mend</strong> restores health.</p><p>Each ordinary action builds Isha’s resonance. At 3, <strong>Moth & metal</strong> deals a powerful hit and heals you. It doesn’t interrupt a heavy attack.</p><p>Health and breath refill before every battle. If you fall, retry from that encounter. Story mode in Settings makes enemies gentler.</p><p class="muted">Click or tap to play. Keyboard: 1–5 choose actions, Space continues dialogue, J opens the journal, M toggles sound, Esc closes a dialog.</p><button class="primary" data-ui="close">I’m ready <span>→</span></button>`);}
function journal(){const s=state||saved;openDialog('The notes we carry',`<p>A record of Oshn, Isha, and a world learning to move again.</p><div class="journey-map">${CHAPTERS.map((c,i)=>`<div class="journey-stop ${s&&i<=s.chapter?'active':''}"><b>${['I','II','III'][i]}</b><span>${esc(c.location)}</span></div>`).join('')}</div>${s?`<p>${s.battlesWon} of 6 notes returned · ${s.memories.kept+s.memories.released} memories found</p>${s.journal.map(j=>`<div class="journal-item"><strong>${esc(j.title)}</strong><p>${esc(j.text)}</p></div>`).join('')||'<p>The first page is waiting for you.</p>'}`:'<p>The first page is waiting for you.</p>'}<button class="primary" data-ui="close">Back to the journey</button>`);}
function settings(){openDialog('Make yourself at home',`<div class="setting-row"><span>Music & sound</span><button class="secondary" data-ui="settings-audio">${prefs.sound?'On':'Off'}</button></div><div class="setting-row"><span>Reduce motion</span><button class="secondary" data-ui="motion">${prefs.reduced?'On':'Off'}</button></div>${state?`<div class="setting-row"><span>Adventure difficulty</span><select id="difficulty" aria-label="Adventure difficulty"><option value="normal" ${state.difficulty==='normal'?'selected':''}>Adventure</option><option value="story" ${state.difficulty==='story'?'selected':''}>Story · gentler battles</option></select></div><p>Difficulty changes apply after the currently shown enemy move, or immediately when you retry. Current damage is always shown.</p>`:''}<p>Your progress is saved in this browser. Clearing browser data will remove it. Sound begins only after you start or resume.</p><button class="secondary" data-ui="home">Return to title</button>`);}
function credits(){openDialog('Behind the bell',`<p><em>The Last Bell of Xenaland</em> is a complete, original little adventure made for Lester, who wanted another journey with the wonder of a painted world and the thoughtfulness of turn-based battles.</p><p>Original story, characters, game design, code, and procedural bell music created for this game. Environment and character paintings generated with OpenAI’s image tool. Isha is an original animated vector illustration.</p><p>No characters, plot, artwork, music, or other assets from <em>Child of Light</em> are used. This is an independent game, unaffiliated with Ubisoft.</p><p>Typography: Cormorant Garamond and DM Sans, with local system fallbacks.</p><p><a href="https://github.com/lestercrafton/dumbai/tree/main/aster" target="_blank" rel="noopener" style="color:var(--gold)">The game’s source in dumbai ↗</a></p><button class="primary" data-ui="close">Carry the morning with you</button>`);}
function start(mode,resume=false){clearTimeout(timer);busy=false;state=resume?saved:createGame(mode);title=false;save();dialog.close();startAudio(prefs.sound);render();}
function newGame(){openDialog(saved?'Begin a new journey?':'Every journey has its own pace',`${saved?'<p>A new journey will replace the saved adventure in this browser.</p>':''}<button class="mode-choice" data-mode="normal"><strong>Adventure</strong><small>Thoughtful battles. Read the enemy, find your rhythm, and use every tool.</small></button><button class="mode-choice" data-mode="story"><strong>Story</strong><small>Gentler battles. More room to linger in the world and enjoy the journey.</small></button><span class="audio-note">Headphones recommended · You can change difficulty at any time.</span>`);}
function perform(id){if(title||busy||dialog.open)return;const legal=actions(state).find(a=>a.id===id&&!a.disabled);if(!legal)return;const old=state,wasBattle=old.phase==='battle';state=act(state,id);save();sound(state.phase==='reward'?'win':state.effect?.kind==='transform'?'harmony':id);render();document.querySelector('#announcer').textContent=state.phase==='story'?state.story[state.storyIndex].text:state.log?.slice(-3).join(' ')||state.phase;
 if(old.storyAfter==='ending'&&old.storyIndex===5&&id==='next'){sound('win');const dawn=document.createElement('div');dawn.className='harmony-flash';app.append(dawn);setTimeout(()=>dawn.remove(),1200);}
 if(wasBattle){busy=true;app.querySelectorAll('[data-action]').forEach(b=>b.disabled=true);const target=app.querySelector(state.effect?.target==='hero'?'.hero-actor':'.enemy-actor');if(id==='strike')app.querySelector('.hero-actor')?.classList.add('attack');if(target){target.classList.add(id==='mend'?'healing':'hit');const pop=document.createElement('div');pop.className='damage-pop';pop.textContent=state.effect?.text||'';target.append(pop);}if(['chime','harmony'].includes(id)){const wave=document.createElement('div');wave.className=id==='harmony'?'harmony-flash':'ring-wave';app.append(wave);}if(state.hero.hp<old.hero.hp)setTimeout(()=>app.querySelector('.hero-actor')?.classList.add('hit'),250);timer=setTimeout(()=>{busy=false;render();},prefs.reduced?100:680);}
 if(state.phase==='battle'&&old.phase!=='battle'&&!prefs.tutorial){prefs.tutorial=true;savePrefs();help();}
}
function ui(action){if(action==='close'){dialog.close();return;}if(action==='audio'||action==='settings-audio'){prefs.sound=!prefs.sound;setAudio(prefs.sound);savePrefs();render();if(action==='settings-audio')settings();return;}sound('ui');if(action==='resume'){start(saved.difficulty,true);return;}if(action==='new'){newGame();return;}if(action==='home'){if(state)save();title=true;dialog.close();render();return;}if(action==='help'){help();return;}if(action==='journal'){journal();return;}if(action==='settings'){settings();return;}if(action==='credits'){credits();return;}if(action==='motion'){prefs.reduced=!prefs.reduced;savePrefs();settings();return;}if(action==='battlelog')openDialog('The last exchange',state.log.map(t=>`<p>${esc(t)}</p>`).join('')+'<button class="primary" data-ui="close">Back to battle</button>');}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled)return;if(b.dataset.ui)ui(b.dataset.ui);else if(b.dataset.mode)start(b.dataset.mode);else if(b.dataset.action)perform(b.dataset.action);});
document.addEventListener('change',e=>{if(e.target.id==='difficulty'&&state){state={...state,difficulty:e.target.value};save();render();}});
document.addEventListener('keydown',e=>{if(e.repeat||e.ctrlKey||e.metaKey||e.altKey||e.target.matches('input,textarea,select'))return;if(dialog.open)return;if(e.code==='Space'&&!title){const opts=actions(state);if(opts.length===1){e.preventDefault();perform(opts[0].id);}}if(/^[1-5]$/.test(e.key)&&!title){e.preventDefault();const a=actions(state)[Number(e.key)-1];if(a)perform(a.id);}if(e.key.toLowerCase()==='j')journal();if(e.key.toLowerCase()==='m')ui('audio');});
dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});
for(let i=0;i<28;i++){const m=document.createElement('span');m.className='mote';m.style.left=`${(i*37)%100}%`;m.style.animationDelay=`-${i*.8}s`;m.style.animationDuration=`${12+i%8*2}s`;document.querySelector('#motes').append(m);}
for(const b of backgrounds){const img=new Image();img.src=`./assets/${b}.webp`;}
savePrefs();render();
